add reading of active cover amount from chain
NexusMutual/quote-api pull request #18
Opened 2020-10-16 12:42 UTC by danoctavian

2020-10-19 12:11 UTC, shark0der requested changes

2020-10-19 12:11 UTC, shark0der commented on src/quote-engine.js
> +      return amounts;
This might get limit rekt by the API. Let's make these sequential but still keep Promise.all for currencies.

2020-10-19 12:11 UTC, shark0der commented on src/routes.js
> +async function isOriginAllowed (origin) {
Let's make this a middleware and remove `const isAllowed = await isOriginAllowed(origin);` from all routes

2020-10-19 12:11 UTC, shark0der commented on src/quote-engine.js
> +    ;
Either put the last `)` on a new line, or put everything on a single line. Could save some space renaming `coverAmount` to `c` inside the map.

2020-10-19 12:14 UTC, horodnicdragos commented on src/routes.js
> +    const isAllowed = await isOriginAllowed(origin);
I think these two lines could be moved to a middleware instead.

2020-10-19 13:24 UTC, danoctavian commented on src/quote-engine.js
> +const CURRENCIES = ['ETH', 'DAI'];
i think constants should generally stay where they are used, but if we use this structure i'll follow along

2020-10-19 19:40 UTC, danoctavian commented on src/routes.js
> +async function isOriginAllowed (origin) {
adressed

2020-10-20 08:35 UTC, shark0der approved these changes

2020-10-20 09:14 UTC, horodnicdragos approved these changes

2020-10-20 10:07 UTC, merged